equinor/webviz

- backend/src/fastapi_app/auth/auth_helper.py
- backend/src/fastapi_app/config.py
- docker-compose-prod.yml
- docker-compose.yml
- radixconfig.yml
Hardcode most variables in config.py instead of using environment variables.
Done in preparation for testing against new SUMO data and new sumo explorer where we will have to temporarily switch to SUMO dev service.
Also, there should be no need for keeping `TENANT_ID` and `CLIENT_ID` secret.
Not so clear on the scope resouce IDs, but for now, work around it by grabbing the SUMO resource ID from sumo wrapper package. The SMDA resource ID is still read from the environment, but note that it is currently not being used.
> Hardcode most variables in config.py instead of using environment

- backend/src/fastapi_app/main.py
- backend/src/fastapi_app/routers/explore.py
- backend/src/fastapi_app/routers/timeseries/router.py
For now, add tags when mounting routers instead of specifying it per endpoint.
Makes sense since we're only using them on a per router basis anyway
> Add tags when mounting routers

- frontend/src/framework/Workbench.ts
- frontend/src/framework/WorkbenchServices.ts
- frontend/src/framework/components/TopNavBar/topNavBar.tsx
- frontend/src/modules/DbgWorkbenchSpy/implementation.tsx
- frontend/src/modules/SimulationTimeSeries/loadModule.tsx
- frontend/src/modules/SimulationTimeSeries/queryHooks.tsx
- frontend/src/modules/SimulationTimeSeries/settings.tsx
- frontend/src/modules/SimulationTimeSeries/state.ts
- frontend/src/modules/SimulationTimeSeries/view.tsx
Added ensemble selection in nav bar, for now just immediate selection of a single ensemble.
Selected ensemble is communicated through `WorkbenchServices` on the `navigator.ensembles` topic.
Communication is through an array of ensembles, but currently only an empty array or an array with a single item will be communicated.
Adapted `SimulationTimeSeries` to use the ensemble selection from the nav bar.
> Allow selection of ensemble in top nav bar

- backend/src/fastapi_app/auth/auth_helper.py
- backend/src/fastapi_app/routers/explore.py
- backend/src/fastapi_app/routers/general.py
- backend/src/fastapi_app/routers/inplace_volumetrics/router.py
- backend/src/fastapi_app/routers/parameters/router.py
- backend/src/fastapi_app/routers/surface/converters.py
- backend/src/fastapi_app/routers/surface/router.py
- backend/src/fastapi_app/routers/timeseries/converters.py
- backend/src/fastapi_app/routers/timeseries/router.py
- backend/src/services/sumo_access/dev_sumo_access_test_driver.py
- backend/src/services/sumo_access/inplace_volumetrics_access.py
- backend/src/services/sumo_access/parameter_access.py
- backend/src/services/sumo_access/summary_access.py
- backend/src/services/sumo_access/surface_access.py
I think this reduces mental load when we are to understand where a file is located in the backend.
Basically `from .something.something` is fine, but changed `from ..something`, `from ...something`, `from ....something` etc. to non-relative imports.
> Limit relative import to same folder

- frontend/src/framework/Module.tsx
- frontend/src/framework/ModuleContext.ts
- frontend/src/framework/ModuleInstance.ts
- frontend/src/modules/Map/MapSettings.tsx
- frontend/src/modules/SimulationTimeSeries/settings.tsx
Converted ModuleContext into a class and changed the `ModuleContext.stateStore` property into a regular method  `ModuleContext.getStateStore()`
> Convert ModuleContext into a class

- backend/src/backend/primary/main.py
- backend/src/backend/user_session/main.py
`orjson` is significantly faster than `json` from std.lib. The difference is significant for lager JSON objects (which often is the case in FMU). Use this as default encoder.
Closes #118.
> Use `orjson` as default encoder

- frontend/.eslintrc.cjs
- frontend/compress_static.cjs
- frontend/src/modules/InplaceVolumetrics/settings.tsx
- frontend/src/modules/Map/MapSettings.tsx
- frontend/src/modules/Map/MapView.tsx
- frontend/src/modules/SimulationTimeSeries/settings.tsx
- frontend/src/modules/TimeSeriesParameterDistribution/settings.tsx
- frontend/src/shared-utils/vtkUtils.ts
Closes #139.
Currently we only use `console.log` for log output. Should use the different levels (`debug`, `info`, `warn`, `error`) in order for the developer to be able to filter on severity in browser console.
> Give `console` level information

- .dockerignore
Reduces build time of Docker images locally by reducing the context of the `COPY` command.
We will also to a larger extent be able to use already cached build layers locally.
Closes #164.
> Added `.dockerignore`

- frontend/package-lock.json
- frontend/package.json
Closes #158.
This ensures we are aligned with `webviz-subsurface-components` development again.
Map (still) works locally, but unfortunately it does **_not_** solve #96 - should probably first revisit that issue when the `webviz-subsurface-components` are split into smaller npm packages.
> Use official `webviz-subsurface-components` `npm` namespace

- backend.Dockerfile
We can remove this now after https://github.com/equinor/fmu-sumo/pull/183.
We can/will do proper pinning of `fmu-sumo` and `sumo-wrapper-python` after https://github.com/equinor/fmu-sumo/issues/182.
> Revert `fmu-sumo` workaround

- frontend/.eslintrc.cjs
- frontend/src/framework/components/ChannelSelect/channelSelect.tsx
- frontend/src/lib/components/Button/button.tsx
- frontend/src/lib/components/IconButton/iconButton.tsx
- frontend/src/lib/components/Input/input.tsx
- frontend/src/lib/components/Slider/slider.tsx
- frontend/src/lib/components/ToggleButton/toggleButton.tsx
Removed the esling react/destructuring-assignment rule and removed line-specific eslint rule disabling comments (eslint-disable-next-line)
> Removed react/destructuring-assignment eslint rule

- backend.Dockerfile
Since we do not have any packages installed directly from `git` anymore, we can re-introduce `poetry` hashes.
> Include hashes in auto-generated `requirements.txt`

- frontend/src/framework/Module.tsx
- frontend/src/framework/ModuleInstance.ts
- frontend/src/framework/ModuleRegistry.ts
- frontend/src/framework/StateStore.ts
- frontend/src/modules/DbgWorkbenchSpy/loadModule.tsx
- frontend/src/modules/DistributionPlot/loadModule.tsx
- frontend/src/modules/Grid3D/loadModule.tsx
- frontend/src/modules/Grid3DIntersection/loadModule.tsx
- frontend/src/modules/InplaceVolumetrics/loadModule.tsx
- frontend/src/modules/Map/loadModule.tsx
- frontend/src/modules/MyModule/loadModule.tsx
- frontend/src/modules/MyModule2/loadModule.tsx
- frontend/src/modules/Pvt/loadModule.tsx
- frontend/src/modules/Sensitivity/loadModule.tsx
- frontend/src/modules/SimulationTimeSeries/loadModule.tsx
- frontend/src/modules/SimulationTimeSeriesSensitivity/loadModule.tsx
- frontend/src/modules/TimeSeriesParameterDistribution/loadModule.tsx
For clarity, rename the `initialState` concept in the framework to `defaultState`. 
Done to prepare for upcoming introduction of a new concept called `initialSettings` in PR #226
> Renamed the initialState concept in framework to defaultState

- frontend/package.json
We have a lot of warnings for unused imports/variables. Whenever merging into main, we should make sure that all warnings are taken care of. If any warning cannot be fixed, it can be explicitly ignored by using eslint comment commands.
> Set `max-warnings` to 0 for eslint

- .github/workflows/webviz.yml
- frontend/.dependency-cruiser.cjs
- frontend/package-lock.json
- frontend/package.json
Dependency cruiser (https://www.npmjs.com/package/dependency-cruiser, https://snyk.io/advisor/npm-package/dependency-cruiser) is making sure that:
- Files in `src/framework/internal` are not used outside of `src/framework`
- Files in `src/lib` do not import any files from other directories in the source tree (goal is to keep them generic)
- Files in `src/modules/_shared` can only be imported from files within `src/modules`
Added `depscheck` script to `package.json` and included it in `validate` script.
> Added `dependency-cruiser` with custom rules for guaranteeing sane environment

- frontend/src/modules/SimulationTimeSeries/preview.tsx
Removed invalid `}` at end of svg path `d` attribute.
> Fixed bug in preview of distribution plot

- backend/src/backend/config.py
- backend/src/services/sumo_access/_helpers.py
- docker-compose-prod.yml
- docker-compose.yml
Until we completely move to the Sumo prod environment, we need an env variable to switch between dev and prod.
Added `WEBVIZ_SUMO_ENV` with default set to dev.
> Add env variable for Sumo environment

- frontend/src/App.tsx
- frontend/src/framework/Module.tsx
- frontend/src/framework/Workbench.ts
This fixes issues with React 18 calling `useEffect` in `App` twice and adding data channels etc. twice.
> Moving module instance number control to `Workbench` and clearing layout on unmount in `App`

- frontend/src/modules/Sensitivity/sensitivityChart.tsx
`Number.MIN_VALUE` is larger than zero causing the axis ranges to be [-Number.MIN_VALUE, Number.MAX_VALUE] which Plotly does not handle.
> Sensitivity Module - Handle data series with only 0 values

- backend/poetry.lock
- backend/pyproject.toml
- backend/src/backend/primary/routers/explore.py
- backend/src/backend/primary/routers/surface/converters.py
- backend/src/services/sumo_access/parameter_access.py
- backend/src/services/sumo_access/summary_types.py
- backend/src/services/sumo_access/surface_polygon_types.py
- backend/src/services/sumo_access/surface_types.py
- backend/src/services/utils/well_completion_utils.py
Upgraded mypy to version 1.5.1 in preparation for introducing new versions of FastAPI and Pydantic
> Upgraded to mypy version 1.5.1

- frontend/src/framework/EnsembleParameters.ts
- frontend/src/framework/internal/EnsembleSetLoader.ts
- frontend/src/lib/utils/MinMax.ts
- frontend/tests/unit-tests/EnsembleParameters.test.ts
- frontend/tests/unit-tests/MinMax.test.ts
* Extended functionality in EnsembleParameters class
* Introduced MinMax class for storing a min/max range
> Extended functionality in EnsembleParameters

- frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
Use selectedNodes instead of selectedTags to allow usage of wildcard
> Fix wildcard usage for VectorSelector in SimulationTimeSeriesMatrix

- frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
- frontend/src/framework/internal/components/Content/private-components/layout.tsx
- Two event handlers not removed in `layout.tsx`
- Stopping event propagation in `header.tsx` on pointer up
---
Visible bugs:
- Jumping to modules list when removing module (although there are still modules left in the layout)
- Removing module by clicking on cross always opened module settings (not wanted when adding/removing modules and having modules list open)
> Fixed two bugs in GUI

- backend/pyproject.toml
- backend/src/backend/primary/routers/correlations/router.py
- backend/src/backend/primary/routers/general.py
- backend/src/backend/primary/routers/grid/router.py
- backend/src/backend/primary/routers/pvt/converters.py
- backend/src/backend/primary/routers/pvt/router.py
- backend/src/backend/primary/routers/surface/converters.py
- backend/src/backend/primary/routers/well/router.py
- backend/src/backend/primary/user_session_proxy.py
- backend/src/backend/user_session/routers/grid/router.py
Closes https://github.com/equinor/webviz/issues/356.
> Fix `pylint` errors

- frontend/src/framework/Ensemble.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/loadModule.tsx
- frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
- frontend/src/modules/SimulationTimeSeriesMatrix/state.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/fanchartPlotting.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/statisticsPlotting.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesContinuousParameterColoring.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesVectorListHelper.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/parameterColoringUtils.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/utils/subplotBuilder.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Add coloring of realization by parameter for selected vectors.
- `EnsemblesContinuousParameterColoring` - Utility class to work with the parameter values across multiple selected ensembles.
- Min/Max parameter value found across selected ensembles.
- Access to parameter value for specific realization in specific ensemble
-  Subplot builder: 
- ColorScale legend
- Grey fallback color if parameter does not exist in ensemble.
- `createVectorTracesUtils.py` - Refactored by creating types for function argument options. To easier work with optional and default arguments.
----
Closes: #219
> Add color by parameter for SimulationTimeSeriesMatrix

- README.md
- backend/src/backend/auth/auth_helper.py
- docker-compose.yml
> Add support for using GitHub codespace

- backend/src/backend/primary/main.py
- backend/src/backend/primary/routers/seismic/converters.py
- backend/src/backend/primary/routers/seismic/router.py
- backend/src/backend/primary/routers/seismic/schemas.py
- backend/src/services/sumo_access/seismic_access.py
- backend/src/services/sumo_access/seismic_types.py
- frontend/src/api/ApiService.ts
- frontend/src/api/index.ts
- frontend/src/api/models/SeismicCubeMeta.ts
- frontend/src/api/models/SeismicMeta.ts
- frontend/src/api/services/SeismicService.ts
Closes https://github.com/equinor/webviz/issues/350
The access class has two functions
- Retrieve a list of all seismic cubes (seismic directory)
- Retrieve the vds handle for a given cube
One endpoint for retrieving the seismic directory is added
The endpoint can be tested on `5c9d06e4-87b1-4ddb-9fa0-11d55b88db8c` in `prod`
Endpoints for retrieving the vds handle and querying the vds-slice service will be added in https://github.com/equinor/webviz/pull/319
> Add SeismicAccess

- backend/src/backend/primary/routers/grid/schemas.py
- backend/src/backend/primary/routers/surface/converters.py
- backend/src/backend/primary/routers/surface/router.py
- backend/src/backend/primary/routers/surface/schemas.py
- backend/src/backend/user_session/routers/grid/router.py
- backend/src/services/utils/b64.py
- backend/src/services/utils/surface_to_float32.py
- frontend/src/api/index.ts
- frontend/src/api/models/B64FloatArray.ts
- frontend/src/api/models/B64UintArray.ts
- frontend/src/api/models/GridSurface.ts
- frontend/src/api/models/SurfaceData.ts
- frontend/src/modules/Grid3D/queryDataTransforms.ts
- frontend/src/modules/Grid3D/queryHooks.ts
- frontend/src/modules/Grid3D/view.tsx
- frontend/src/modules/Map/MapView.tsx
- frontend/src/modules/SubsurfaceMap/queryHooks.tsx
- frontend/src/modules/SubsurfaceMap/view.tsx
- frontend/src/modules/_shared/Surface/queryDataTransforms.ts
- frontend/src/modules/_shared/Surface/queryHooks.ts
- frontend/src/modules/_shared/base64.ts
Established utilities and conventions for communicating binary array data embedded in json using base64
Currently transformation from base64 strings to array data is done using React Query's `select` mechanism.
We should probably look into perfroming this conversion as part of the actual data fetching promise instead, see issue #385
> Support sending of binary arrays using base64 encoding

- frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
With the whole module preview div being draggable now, the user might click on an image and trigger the browser's default image dragging (can e.g. be used for quickly saving images from a website on the local computer by dragging it out of the browser and inside a file explorer instance or to quickly open it in another application). Added an invisible non-selectable layer on top of all preview images in order to suppress this undesired feature.
> Added overlay in order to prevent images from being draggable

- .github/workflows/webviz.yml
- frontend/package.json
Closes #402. Moved the `NODE_OPTIONS` setting to `package.json` such that it can be reused both in GitHub actions and during e.g. local and Radix build of the docker production container. Also doubled the size, since the current value sometimes is not enough (both in GitHub action and Radix).
> Increase allowed memory during build, also in Radix

- backend/src/backend/user_session/routers/general.py
- frontend/src/framework/internal/components/NavBar/navBar.tsx
- frontend/src/framework/internal/components/NavBar/private-components/UserSessionState.tsx
Related to #362.
- Replaced the "⭐ GitHub" in the menu with CPU/memory metrics of the user session backend.
- Uses `psutils` in backend to report container stats (https://github.com/giampaolo/psutil/issues/1011#issuecomment-513715809).
- Uses `react-query` on frontend to fetch container status every two seconds. React-query refetches only when user has the browser tab focused. Locking the screen or going away from the tab stopes the refetching, and therefore also starts the countdown for stopping the user session backend.
> Show live CPU and memory usage of user session backend

- frontend/src/framework/InitialSettings.ts
- frontend/src/framework/Workbench.ts
- frontend/src/framework/components/ChannelSelect/channelSelect.tsx
- frontend/src/modules/DistributionPlot/settings.tsx
- frontend/src/modules/SimulationTimeSeries/channelDefs.ts
- frontend/src/modules/TornadoChart/settings.tsx
- frontend/src/templates/oatTimeSeries.ts
- `Workbench` cannot reset module instance count as it is used as a `key` property for React and would prevent a proper remount of the respective components
- `applyToStateOnMount` needs to be move out of possibly undefined `InitialSettings` and take it as an argument, such that it is always called and the check for `undefined` is moved into the respective `useEffect` (this caused #306)
- `ChannelSelect` did not react to updates to its `initialChannel` property and had a missing dependency in its `useEffect` causing issues when initialising e.g. `TornadoPlot` in a template
Closes #306.
> Multiple bug fixes and improvements related to initial settings, templates, and `ChannelSelect`

- frontend/src/modules/Grid3D/loadModule.tsx
- frontend/src/modules/Grid3D/queryHooks.ts
- frontend/src/modules/Grid3D/settings.tsx
- frontend/src/modules/Grid3D/state.ts
- frontend/src/modules/Grid3D/view.tsx
Some minor fixes to the 3d grid module:
- Reverse z-axis as per changes to the subsurface-viewer component
- Use global color scale
- Add drilled well trajectories
> Fixes to 3dGrid module

- frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
When e.g. closing the ensemble dialog, the module below the cross icon button would become activated although no full click on the module was performed.
> Bugfix: Pointer up on module was enough to activate it

- frontend/src/lib/components/Select/select.tsx
- frontend/src/lib/components/Virtualization/virtualization.tsx
- Improved `startIndex` handling in `Virtualization`, fixes #394
- Removed auto `minWidth` handling in `Select`, fixes #373 
- Moved shift handling function out of focus check if statement, fixes #377
> `Select` and `Virtualization` fixes

- backend/src/backend/primary/routers/explore.py
- backend/src/services/sumo_access/sumo_explore.py
> Remove hardcoded Drogon field/case selection

- frontend/src/modules/SimulationTimeSeriesSensitivity/settings.tsx
- frontend/src/modules/TornadoChart/loadModule.tsx
- frontend/src/modules/TornadoChart/sensitivityResponseCalculator.ts
- frontend/src/modules/TornadoChart/sensitivityTable.tsx
- frontend/src/modules/TornadoChart/settings.tsx
- frontend/src/modules/TornadoChart/state.ts
- frontend/src/modules/TornadoChart/view.tsx
Tries to set to set `rms_seed` as reference, if not picks the first sensitivity found.
The reference can then be changed from a dropdown in the TornadoChart module.
Closes #465
> Allow change of reference sensitivity in TornadoChart/Table

- frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
- frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Correct/fix warning messages to show correct content
- Ensure warning message with non existing vectors when selecting single ensemble without vectors.
- Only show message for non-existing vector observations when `showObservations` is selected/true
> Adjust warning message for statusWriter in SimulationTimeSeriesMatrix module

- radixconfig.yml
As primary and session code shares same config and code, this env var is necessary.
> Add vds envvar to user session

- frontend/package-lock.json
- frontend/package.json
Closes https://github.com/equinor/webviz/issues/507.
Vite 5 introduces no breaking changes for consumers. They have introduced a depracation warning for projects not using `"type": "module"` in their `package.json`, however, we already have this included 👍
> Update to latest `vite` major

- frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
- frontend/src/modules/ParameterDistributionMatrix/settingsToViewInterface.ts
- frontend/src/modules/ParameterDistributionMatrix/typesAndEnums.ts
- frontend/src/modules/ParameterDistributionMatrix/view/components/ParameterDistributionPlot.tsx
- frontend/src/modules/ParameterDistributionMatrix/view/view.tsx
- frontend/src/modules/_shared/statistics.ts
- Show individual realization values (check box enabling), with hover info
- Show P10, mean and P90 as markers, i.e. x-symbols along the 0-axis for the ensemble (check box enabling).
- Bug fixes
> Parameter distribution Matrix show underlying data

- frontend/src/lib/hooks/useElementBoundingRect.ts
Set `useCapture` to true in order to capture all scroll events for any child of `window`.
> Fixed bug where scrolling is not detected

- frontend/src/framework/components/RealizationPicker/realizationPicker.tsx
Fix bug for realizaiton picker, allow realization number 0 in input. Realization number = 0 gave error for both single value and range `a-b` input.
> Fix bug in RealizationPicker component

- frontend/src/modules/SimulationTimeSeries/view/atoms/atomDefinitions.ts
- frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Add enable flag for fetching individual realization data for `SimulationTimeSeries`- and `SimulationTimeSeriesMatrix`-module
Closes: #632
> Simulation Time Series: Prevent unnecessary fetch of individual realization data

- backend_py/primary/primary/services/sumo_access/case_inspector.py
There is a bug in Sumo Explorer's `Case.iterations_async`
Revert back to using the sync version of `Case.iterations` instead of `Case.iterations_async` until this has been remedied.
See also: https://github.com/equinor/fmu-sumo/issues/326
> Work around bug in Sumo Explorer that reports too few iterations/ensembles

- backend_py/primary/primary/services/sumo_access/queries/grid3d.py
> Use term filter instead of match for exact keyword matches when finding grid data uuids in elastic search

- frontend/src/lib/components/RadioGroup/radioGroup.tsx
Decrease the gap, as items takes up too much space.
Vertically: gap-1 seems to be a reasonable gap
Horizontally: gap-3 seems suitable to separate text of a radio group element to the radio button of next radio group element.
Closes: #743
> Adjust gap for RadioGroup component

- frontend/src/framework/GuiMessageBroker.ts
- frontend/src/framework/internal/components/EnsembleRealizationFilter/ensembleRealizationFilter.tsx
- frontend/src/framework/internal/components/EnsembleRealizationFilter/private-components/realizationNumberDisplay.tsx
- frontend/src/framework/internal/components/NavBar/rightNavBar.tsx
- frontend/src/framework/internal/components/RightSettingsPanel/private-components/RealizationFilterSettings/realizationFilterSettings.tsx
- frontend/src/framework/internal/components/RightSettingsPanel/rightSettingsPanel.tsx
- frontend/src/framework/internal/components/SettingsContentPanels/settingsContentPanels.tsx
- frontend/src/framework/types/unsavedChangesAction.ts
- frontend/src/framework/utils/objectUtils.ts
- frontend/tests/unit/objectUtils.test.ts
> 800 fix minor realization filter issues

- backend_py/primary/primary/routers/polygons/router.py
- backend_py/primary/primary/routers/surface/router.py
- backend_py/primary/primary/routers/well/router.py
- backend_py/primary/primary/utils/drogon.py
For all the "drogon or not" checks done in the router, we're manually writing out the identifier strings. This is error prone, and a bit cumbersome; I instead added small utility to keep these string checks in one place
> Refactoring - Added utility to simplify drogon identifier comparisons

- backend_py/primary/primary/routers/surface/schemas.py
- backend_py/primary/primary/routers/well/converters.py
- backend_py/primary/primary/routers/well/schemas.py
- frontend/src/api/models/StratigraphicUnit.ts
There was two `StratigraphicUnit` schemas. The one in the well-router was not used, so I removed it
> Refactor - Removed unused duplicated strat unit schema

- .github/workflows/webviz.yml
- Pin version to `1.8.5`
- Adjust deprecated command
---
1) Workflow failed after poetry update `2.0.0`. Pin version to `1.8.5` for now, and crated a separate issue to update to `2.0.0`: https://github.com/equinor/webviz/issues/839
2) Deprecated command `poetry lock --check --no-update` replaced with `poetry check --lock`
---
Closes: #837
> Pin poetry to v `1.8.5` and fix deprecated poetry workflow command

- backend_py/primary/primary/routers/vfp/schemas.py
- frontend/src/api/autogen/types.gen.ts
- frontend/src/modules/Vfp/utils/vfpDataAccessor.ts
- frontend/src/modules/Vfp/utils/vfpTableClassifier.ts
Update for improved type safety with new api generator handling back-end string literal to union of strings in front-end. E.g.: `Literal["PROD", "INJ"]`-> "PROD" | "INJ"
Closes: #874
> Make use of Literal in back-end schema for vfp type

- frontend/src/lib/components/Slider/slider.tsx
Fixed slider bugs.
Replaced label code, with slot named `valueLabel` for mui-base `Slider`-component. Render a `Popper`-component for the label.
Thereby there is no need to calculate positioning of label component anymore.
---
Closes: #777
Closes: #645
> Adjust slider component

- backend_py/primary/primary/services/vds_access/vds_access.py
The following renaming was requested by pylint but it changes how the metadata dataclass needs to be instantiated:
- x -> x_axis 
- y -> y_axis
> Fix related to pylint required change to names of axes

- frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
- frontend/src/lib/components/CircularProgress/circularProgress.tsx
- frontend/src/lib/components/Dialog/dialog.tsx
- frontend/src/lib/components/Dropdown/dropdown.tsx
- frontend/src/lib/hooks/useElementBoundingRect.ts
Elements were not properly tracked anymore after recent changes. Introduced a new observation pattern utilizing the `IntersectionObserver`. We might want to look at the `Popover API` at some later point of time in order to remove custom code and to stick to the new standard: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API
Also removed unused/unnecessary CSS classes.
> Fix: Issues with element position tracking

- frontend/src/App.tsx
Resolves #942. Adds a disclaimer regarding data sharing and quality to the login page. Also tweaks the existing orange dev notice to mention down-time.
> Added data sharing disclaimer on login screen

- frontend/src/framework/internal/components/LeftSettingsPanel/private-components/templatesList.tsx
Previews with multiple modules of same type cause duplicated key errors.
> fix: insufficient key in template previews

- frontend/src/modules/2DViewer/view/components/LayersWrapper.tsx
- frontend/src/modules/_shared/DataProviderFramework/hooks/useVisualizationProduct.ts
Adds a small hook to make the `VisualizationAssembler.make(...)` function only run when actual data revisions have happened
> [DPF] Visualization assembler product hook

- frontend/src/framework/internal/utils/debug.ts
Made it camel-cased, and swapped the semi-colon with an underscore
> Simplified debug flag string casing

- backend_py/primary/poetry.lock
- backend_py/primary/primary/services/sumo_access/inplace_volumes_table_access.py
- backend_py/primary/primary/services/sumo_access/inplace_volumes_table_types.py
- backend_py/primary/pyproject.toml
Resolves #1061
fmu-dataio split its models to a separate package to more easily expose its models.
> Replace fmu-dataio with fmu-datamodels

- backend_py/primary/primary/auth/auth_helper.py
We previously used `sub`, but `oid` is better suited for relating user created items to the user
> Backend - Make `AuthInfo` use `oid` as user_id

- frontend/src/lib/utils/CancelableQueryRunner.ts
- frontend/src/lib/utils/ScopedQueryController.ts
- frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/ObservedSurfaceProvider.ts
- frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/RealizationGridProvider.ts
- frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/RealizationPolygonsProvider.ts
- frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/RealizationSurfaceProvider.ts
- frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/StatisticalSurfaceProvider.ts
- frontend/src/modules/Intersection/DataProviderFramework/customDataProviderImplementations/RealizationSurfacesProvider.ts
- frontend/src/modules/Intersection/DataProviderFramework/customDataProviderImplementations/SurfacesPerRealizationValuesProvider.ts
- frontend/src/modules/WellLogViewer/DataProviderFramework/dataProviders/plots/_shared.ts
- frontend/src/modules/_shared/DataProviderFramework/dataProviders/implementations/DrilledWellTrajectoriesProvider.ts
- frontend/src/modules/_shared/DataProviderFramework/dataProviders/implementations/DrilledWellborePicksProvider.ts
- frontend/src/modules/_shared/DataProviderFramework/dataProviders/implementations/IntersectionRealizationGridProvider.ts
- frontend/src/modules/_shared/DataProviderFramework/dataProviders/implementations/IntersectionRealizationSeismicProvider.ts
- frontend/src/modules/_shared/DataProviderFramework/framework/DataProvider/DataProvider.ts
- frontend/src/modules/_shared/DataProviderFramework/interfacesAndTypes/customDataProviderImplementation.ts
This gives a more Tanstack-Query-native experience and fits better into the ecosystem. Cancellation is automatically performed by Tanstack when there are no more observers for a query. This plays well with `useQuery` hooks and `atomWithQuery/ies` as we let the QueryCache handle everything.
> [DPF]: Improve cancellation logic by tightening query fetches to Tanstack QueryObserver

- backend_py/primary/primary/routers/inplace_volumes/router.py
Closes: #1095
Note: Was only for the deprecated inplace volumes format
> Fix: Realization filter is ignored for Inplace volumes statistics
