equinor/webviz

.github/workflows/webviz.yml
frontend/compress_static.cjs
nginx.Dockerfile
nginx.conf
radixconfig.yml

Later we extend the GitHub action to tag and push versioned Docker images on releases in the repository.

Initial GitHub action and Dockerfiles

---

frontend/src/framework/ModuleInstance.ts
frontend/src/framework/providers/QueryClientProvider.tsx

* Epose the state store in ModuleContext
* Add react devtools to App

Expose StateStore in ModuleContext

---

radixconfig.yml

Enable Azure key vault in Radix

---

docker-compose.yml
radixconfig.yml

For now during development `ALLOW_EMPTY_PASSWORD` on internal Redis instance...

Add Redis to Radix

---

backend/src/fastapi_app/routers/timeseries.py
backend/src/fastapi_app/schemas/timeseries.py
backend/src/services/summary_vector_statistics.py
backend/src/services/sumo_access/dev_sumo_access_test_driver.py
backend/src/services/sumo_access/summary_access.py
frontend/src/api/index.ts
frontend/src/api/models/StatisticFunction.ts
frontend/src/api/models/StatisticValueObject.ts
frontend/src/api/models/VectorStatisticData.ts
frontend/src/api/services/TimeseriesService.ts
frontend/src/framework/WorkbenchServices.ts

Added vector statistics, currently implemented using Pandas.
Currently it seems that pyarrow does not have the complete set of statistical functions needed, but might want to look into numpy?

Added vector statistic on backend

---

frontend/src/App.tsx
frontend/src/framework/Module.tsx
frontend/src/framework/ModuleInstance.ts
frontend/src/framework/ModuleRegistry.ts
frontend/src/framework/StateStore.ts
frontend/src/framework/components/Content/private-components/layout.tsx
frontend/src/framework/components/Settings/settings.tsx
frontend/src/framework/providers/QueryClientProvider.tsx
frontend/src/lib/components/Checkbox/checkbox.tsx
frontend/src/lib/components/Checkbox/index.ts
frontend/src/lib/components/Dropdown/dropdown.tsx
frontend/src/lib/components/LabelComponentGroup/index.ts
frontend/src/lib/components/LabelComponentGroup/labelComponentGroup.tsx
frontend/src/lib/components/ResizablePanels/index.ts
frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
frontend/src/lib/components/Select/select.tsx
frontend/src/main.tsx

- Adjusted setting state method in state store and added optional options object to enable deep state comparison per state
- Fixed bugs and improved Select and Dropdown components 
- Added Label component that can wrap any input component
- Added Checkbox component
- Removed state update on mouseup event in layout component
- Removed state update triggering reinit of QueryProvider

Improved/added components, adjusted state store setting function and fixed rerender issues

---

frontend/src/modules/SimulationTimeSeries/view.tsx

Timeseries, show vector units and changed line style for vectors that represent a rate

---

frontend/src/framework/WorkbenchServices.ts

Always use caching in `WorkbenchServices`, and always compress the values (remove duplicates).
We may have to refine this and allow opt-in or opt-out later, but this should serve as a good default behavior.
Also switch to using Javascrip Map instead of Object

Always cache and compress values in `WorkbenchServices`

---

frontend/src/framework/components/Content/private-components/layout.tsx
frontend/src/framework/components/Content/private-components/modulesList.tsx
frontend/src/framework/components/Content/private-components/viewWrapper.tsx
frontend/src/lib/components/Dropdown/dropdown.tsx
frontend/src/lib/components/Virtualization/virtualization.tsx
frontend/src/lib/hooks/useElementSize.ts

- Improved viewWrapper rerender
- Improved Dropdown input onclick behaviour
- Changed module search to case insensitive

Fixed issue with Virtualization render order (not showing all items)

---

docker-compose.yml
frontend/index.html
frontend/src/main.css

Three-line PR just to feel more at home 🏠 
Also added possibility in dev-mode for `index.html` changes to be reflected immediately without having to rebuild `docker` container.

Use Equinor font

---

.github/workflows/webviz.yml
backend/src/fastapi_app/auth/auth_helper.py
backend/src/fastapi_app/auth/enforce_logged_in_middleware.py
backend/src/fastapi_app/main.py
backend/src/fastapi_app/routers/general.py
backend/src/fastapi_app/routers/surface/router.py
backend/src/fastapi_app/routers/timeseries/router.py
backend/src/services/parameter_correlations.py
backend/src/services/sumo_access/inplace_volumetrics_access.py
backend/src/services/sumo_access/parameter_access.py
backend/src/services/sumo_access/surface_access.py
backend/src/services/sumo_access/surface_types.py
backend/src/services/utils/statistic_function.py

Fix type annotations + enable `mypy` in CI

---

.github/workflows/webviz.yml

Add cache of dependencies in GitHub action

---

.github/workflows/webviz.yml
backend/poetry.lock

Closes https://github.com/equinor/webviz/issues/97.

Check consistency between `poetry` lock file and `pyproject.toml`

---

.github/workflows/webviz.yml
backend/poetry.lock
backend/pyproject.toml

Use new `sumo` `git` installation instructions

---

backend/poetry.lock

...as `1.26.4` gives the problem stated in #105.

Downgrade `azure-core` to `1.26.2`

---

backend/poetry.lock

Revert more backend dependency upgrades in order work around #105.

Revert more upgrades in `backend` dependencies

---

nginx.conf

Use `brotli` compression also on dynamic responses

---

.github/workflows/webviz.yml
radixconfig.yml

Radix build from source

---

backend/poetry.lock
backend/pyproject.toml
backend/src/services/summary_vector_statistics.py

Update to `pandas==2` with performance improvements

---

.github/workflows/webviz.yml
frontend-prod.Dockerfile
frontend/.npmrc

Add `.npmrc` to `frontend`

---

nginx.conf

Add CSP and other security headers to `nginx`

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/Button/button.tsx
frontend/src/lib/components/IconButton/iconButton.tsx
frontend/src/lib/components/Input/input.tsx
frontend/src/lib/components/Slider/slider.tsx
frontend/src/lib/components/Switch/switch.tsx
frontend/src/lib/components/ToggleButton/toggleButton.tsx

Support newer versions of `@mui/base`

---

frontend/src/framework/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
frontend/src/framework/components/Content/private-components/ViewWrapper/viewWrapper.tsx

Adjusted component structure in order to avoid unnecessary rerenders

---

frontend/package-lock.json
frontend/package.json
frontend/src/modules/Grid3D/view.tsx
frontend/src/modules/Map/MapView.tsx
frontend/vite.config.ts

Use `@webviz/subsurface-viewer`

---

frontend/package-lock.json
frontend/package.json

Keep zoon and pan in `Map`

---

frontend/src/lib/components/DiscreteSlider/discreteSlider.tsx
frontend/src/lib/components/DiscreteSlider/index.ts
frontend/src/lib/components/Slider/slider.tsx
frontend/src/modules/DistributionPlot/settings.tsx
frontend/src/modules/MyModule/settings.tsx
frontend/src/modules/registerAllModules.ts

Removed internal inputs from slider component (these can be handled from the outside) and added hover value label.

Adjustments to slider component

---

.gitignore

Adjust .gitignore file for vscode settings

Adjust gitignore for `.vscode`

---

frontend/src/modules/registerAllModules.ts

Way to reproduce / test:
- Drag `MyModule` into your layout
- Refresh

[BUGFIX] Dev modules were not imported properly when already part of layout (timing issue)

---

frontend/compress_static.cjs
frontend/package-lock.json
frontend/package.json

- Add `glob` to devDependecies in package.json
- Update usage from `glob` to `glob.glob` in `compress_static.cjs`

Add glob to devDependencies

---

frontend/src/lib/components/SmartNodeSelector/index.ts

Add export of selection type for usage of onChange for both `VectorSelector` and `SmartNodeSelector`

Add export of SmartNodeSelectorSelection

---

frontend/src/framework/components/MultiEnsembleSelect/multiEnsembleSelect.tsx
frontend/src/modules/SimulationTimeSeries/settings.tsx
frontend/src/modules/SimulationTimeSeriesSensitivity/settings.tsx

- Fix bug resulting in single selection functionality
- Update SimulationTimeSeries and SimulationTimeSeriesSensitivity modules to use SIngleEnsembleSelect component
Closes: #294

Fix MultiEnsembleSelect component and update usage

---

frontend/src/GlobalErrorBoundary.tsx
frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
frontend/src/main.tsx

Also separated Module instance's "importing" from "initialising" loading state.

Added global error boundary and recovery functionality

---

backend/src/services/types/well_completion_types.py
frontend/src/modules/WellCompletion/utils/wellCompletionsDataAccessor.ts

Refactored well completion backend and frontend slightly in preparation for introducing new version of FastAPI and Pydantic.
* Removed None as attribute type until we're sure we need it
* Refactored and cleaned up frontend data accessor class in preparation new FastAPI version
There should be no functional changes

Minor refactor of well completion backend and frontend

---

frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx

Increase draggable area to whole module preview

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add custom `devcontainer.json`

---

backend/poetry.lock
backend/pyproject.toml
backend/src/backend/primary/user_session_proxy.py
backend/src/backend/user_session/main.py
backend/src/config.py
docker-compose.yml
radixconfig.yml

Use Redis for existing user sessions

---

backend/poetry.lock
backend/pyproject.toml

Update to fmu-sumo 0.5.4

---

backend/src/backend/primary/user_session_proxy.py
backend/src/backend/shared_middleware.py
backend/src/config.py
docker-compose-prod.yml
docker-compose.yml
radixconfig.yml

Combine into one Redis instance

---

frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx

Fixed visualization bug in `SmartNodeSelector`

---

frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx

Use case insensitive string comparison when filtering on user

---

frontend/src/framework/components/RealizationPicker/index.ts
frontend/src/framework/components/RealizationPicker/realizationPicker.tsx
frontend/src/framework/internal/components/LoginButton/loginButton.tsx
frontend/src/lib/components/Dropdown/dropdown.tsx
frontend/src/lib/utils/textSize.ts

Added a new component for picking realizations in a more user-friendly way than a plain input field. This component is a basic version and might require additional updates/features in order to align with the requirements of further use cases.

Implementation of `RealizationPicker` component

---

frontend/src/App.tsx
frontend/src/framework/internal/components/NavBar/navBar.tsx

Add dev label

---

frontend/src/lib/hooks/useValidArrayState.ts

Prevent re-rendering issue. Ensure reference stability of props/states.
Closes: #517

Fix useValidArrayState hook re-render issue

---

frontend/src/framework/internal/components/DebugProfiler/debugProfiler.tsx

This fixes current issues in GitHub actions.

Fixed issue in `DebugProfiler` due to new @types/react version

---

frontend/src/framework/components/VectorSelector/vectorSelector.tsx
frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
frontend/tests/unit/VectorSelectorUtils.test.ts

Minot adjustment to algorithm for creating vectorSelector data from list of vector names. Improved check in `settings.tsx` to prevent calling create-method unless list of vector names is actually changed.
Also added unit tests.

Improvement create vector selector data from vectors

---

backend/src/services/smda_access/mocked_drogon_smda_access/_mocked_well_access.py
backend/src/services/smda_access/queries/get_well_headers.py
backend/src/services/smda_access/types.py
frontend/src/api/models/WellBoreHeader.ts

Relates to #565 
=> Only show SMDA wells that have a survey. Remove unused metadata.

Only show SMDA wells with survey

---

README.md
radixconfig.yml

Added an additional radix deployment for development code.
For demos and user feedback.

Add Radix dev deployment

---

frontend/src/modules/SimulationTimeSeries/settings/atoms/derivedAtoms.ts
frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx

Adjust settings for `SimulationTimeSeries`- and `SimulationTimeSeriesMatrix`-modules.
Rearrange settings and placed settings below `Visualization` selections to clarify which settings are dependent on currently selected visualization option.
The two collapsible:
- `Statistics Options` - enabled for all statistical visualization modes
- `Color individual realization by parameter` - enabled only for individual realization visualization mode
Made collapsible disabled and collapsed when not applicable. The collapsible is expanded/closed based on the last user selection when applicable visualization mode is selected.

Adjust setting for improved user experience

---

backend_py/primary/primary/routers/surface/converters.py
backend_py/primary/primary/routers/surface/router.py
backend_py/primary/primary/services/sumo_access/surface_access.py
backend_py/primary/primary/services/sumo_access/surface_types.py
backend_py/primary/primary/services/utils/surface_intersect_with_polyline.py

Moved the functionality in `SurfaceAccess.get_realization_surface_intersection_async()` out of the `SurfaceAccess` class and into separate worker function, `intersect_surface_with_polyline()`

Moved surface intersection functionality out of SurfaceAccess class

---

frontend/src/framework/GuiMessageBroker.ts
frontend/src/lib/components/ResizablePanels/resizablePanels.tsx

Fix for crash with storing undefined values in local storage (writing and reading)

---

backend_py/primary/primary/services/sumo_access/group_tree_access.py
backend_py/primary/primary/services/sumo_access/well_completions_access.py
frontend/src/modules/WellCompletions/settings.tsx

- Update to use `to_pandas()`-function rather than attribute for Sumo
- Adjust settings for `WellCompletions`-module. Improved separation, and fix correct disabling of components based on failed queries.
----
Closes: #654

Update sumo to pandas to function and adjust settings for WellCompletions-module

---

backend_py/primary/primary/utils/query_string_utils.py
backend_py/primary/tests/unit/utils/test_query_string_utils.py
frontend/src/lib/utils/queryStringUtils.ts
frontend/tests/unit/queryStringUtils.test.ts

Added utility functions for encoding list of uints and key-value pairs in URL friendly strings

Add utility functions for encoding/decoding list of uints and key-value pairs in URL-friendly strings

---

backend_py/primary/primary/routers/group_tree/schemas.py
backend_py/primary/primary/services/group_tree_assembler/group_tree_assembler.py
frontend/src/modules/FlowNetwork/settings/atoms/derivedAtoms.ts
frontend/src/modules/FlowNetwork/settings/settings.tsx

Make usage of edge/node labels in dropdowns in settings

---

frontend/src/modules/SimulationTimeSeries/view/atoms/atomDefinitions.ts

Add realization filter functionality to SimulationTimeSeries module

---

backend_py/primary/primary/services/sumo_access/parameter_access.py
frontend/src/modules/ParameterDistributionMatrix/settings/atoms/derivedAtoms.ts
frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
frontend/src/modules/ParameterDistributionMatrix/typesAndEnums.ts
frontend/src/modules/ParameterDistributionMatrix/view/components/ParameterDistributionPlot.tsx
frontend/src/modules/ParameterDistributionMatrix/view/view.tsx

- Set max plots to 56
- Filter out log10 in module for now. revisit when metadata is matured.

Parameter fixes

---

frontend/package-lock.json
frontend/package.json

Closes: https://github.com/equinor/webviz/issues/703

Update well-completions-plot version

---

frontend/src/lib/components/DenseIconButton/denseIconButton.tsx
frontend/src/lib/components/DenseIconButton/index.ts

Adds a new lib component for a dense icon button to be used in GUI with limited space.

Implementation of `DenseIconButton`

---

frontend/src/lib/components/Button/button.tsx

Remove string as color type and add "secondary" as option.
Closes: #749

Adjust color prop for Button-component

---

frontend/src/main.tsx
frontend/src/tempMoved/TempMovedToAmsterdamNotifier.tsx
frontend/src/tempMoved/WebvizSpinner/index.ts
frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.css
frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.tsx

`Moved to Amsterdam` notification

---

frontend/src/framework/components/ParameterListFilter/parameterListFilter.tsx
frontend/src/lib/components/IconButton/iconButton.tsx
frontend/src/modules/SimulationTimeSeries/settings/settings.tsx

Improve UX for coloring realizations by parameter value in SimulationTimeSeries-module.
Make dependency between parameter selection and active Individual realization more intuitive.
Also add secondary color for iconButton
---
Now placed together with Visualization selections radio buttons 
----
Closes: #753
Closes: #754

Improve UX for Color realization by parameter in SimulationTimeSeries

---

frontend/src/modules/Rft/settings.tsx
frontend/src/modules/Rft/settings/atoms/derivedAtoms.ts

Changing response or changing well resets other settings due to wrong atoms used.

Fix issue with Rft atoms

---

frontend/src/lib/components/DisclaimerWrapper/disclaimerWrapper.tsx
frontend/src/lib/components/DisclaimerWrapper/index.ts
frontend/src/modules/WellCompletions/view.tsx

793 well completions zone order disclaimer

---

nginx.conf

Needed for viewing maps in 2d viewer

allow png images as dataformat in nginx

---

backend_py/primary/primary/main.py
backend_py/primary/primary/services/graph_access/graph_access.py
backend_py/primary/primary/services/smda_access/_smda_get_request.py
backend_py/primary/primary/services/ssdl_access/_ssdl_get_request.py
backend_py/primary/primary/services/sumo_access/_helpers.py
backend_py/primary/primary/services/surface_query_service/surface_query_service.py
backend_py/primary/primary/services/utils/httpx_async_client_wrapper.py
backend_py/primary/primary/services/vds_access/vds_access.py

* Moved class implementation into service layer
* Renamed global singleton to `HTTPX_ASYNC_CLIENT_WRAPPER`
* Renamed `stop()` to` stop_async()`
* Fixed timeout in `batch_sample_surface_in_points_async()`

Refactor and fix related to HTTPXAsyncClientWrapper

---

backend_py/primary/primary/services/sumo_access/_helpers.py
backend_py/primary/primary/services/sumo_access/case_inspector.py
backend_py/primary/primary/services/sumo_access/grid3d_access.py
backend_py/primary/primary/services/sumo_access/group_tree_access.py
backend_py/primary/primary/services/sumo_access/inplace_volumetrics_access.py
backend_py/primary/primary/services/sumo_access/observation_access.py
backend_py/primary/primary/services/sumo_access/parameter_access.py
backend_py/primary/primary/services/sumo_access/polygons_access.py
backend_py/primary/primary/services/sumo_access/rft_access.py
backend_py/primary/primary/services/sumo_access/seismic_access.py
backend_py/primary/primary/services/sumo_access/summary_access.py
backend_py/primary/primary/services/sumo_access/sumo_client_factory.py
backend_py/primary/primary/services/sumo_access/sumo_inspector.py
backend_py/primary/primary/services/sumo_access/surface_access.py
backend_py/primary/primary/services/sumo_access/table_access.py
backend_py/primary/primary/services/sumo_access/vfp_access.py
backend_py/primary/primary/services/sumo_access/well_completions_access.py
backend_py/primary/primary/services/surface_query_service/surface_query_service.py

Moved `create_sumo_client()` factory function from `_helpers.py` into separate file `sumo_client_factory.py`

Moved `create_sumo_client()` factory function to public module

---

backend_py/primary/poetry.lock
backend_py/primary/primary/services/sumo_access/rft_access.py

Bumps MyPy from 1.9 to 1.15 to resolve an issue I ran into on another branch
The issue in question is this: https://github.com/python/mypy/issues/12009

Updated MyPy to fix type narrowing error

---

frontend/src/main.css

Adds some tailwind configurations that were present in `tailwind.config.cjs`, but were lost when we migrated to version 4

Hotfix: Fix missing tailwind configurations

---

frontend/src/modules/_shared/LayerFramework/framework/DataLayer/DataLayer.ts
frontend/src/modules/_shared/LayerFramework/framework/Group/Group.ts
frontend/src/modules/_shared/LayerFramework/framework/SettingsGroup/SettingsGroup.ts
frontend/src/modules/_shared/LayerFramework/framework/SharedSetting/SharedSetting.ts

Fixes current bug in 2D viewer.

fix: instanceof checks in prod for framework entities

---

frontend/src/modules/2DViewer/view/components/LayersWrapper.tsx

[DPF]: Fix polygon provider exception

---

frontend/src/framework/userCreatedItems/IntersectionPolylines.ts
frontend/src/modules/3DViewer/view/components/SubsurfaceViewerWrapper.tsx
frontend/src/modules/3DViewer/view/view.tsx

Add fieldId to user created polyline

---

frontend/src/modules/_shared/components/EsvIntersection/esvIntersection.tsx

This should fix the issue with `too many WebGL contexts` and the infinite loop.

fix: WebGL context issues

---

backend_py/primary/primary/routers/well/converters.py
backend_py/primary/primary/routers/well/router.py
backend_py/primary/primary/routers/well/schemas.py
backend_py/primary/primary/services/smda_access/smda_access.py
backend_py/primary/primary/services/smda_access/types.py
frontend/src/api/autogen/types.gen.ts
frontend/src/modules/WellLogViewer/settings/atoms/queryAtoms.ts
frontend/src/modules/WellLogViewer/utils/strings.ts

Adds the Azimuth, Inclination, and Dogleg Severity curves to the well log viewer curves.

Well Log Viewer - Add Wellbore survey curves

---

frontend/src/lib/components/Dropdown/dropdown.tsx

Made open dropdowns close when clicking the collapse icon

---

README.md
radixconfig.yml

See https://www.radix.equinor.com/guides/external-alias/

Add external DNS alias in Radix

---

frontend/src/lib/components/Label/label.tsx

Add childrenWrapperClassName prop to Label

---

frontend/src/modules/_shared/DataProviderFramework/visualization/VisualizationAssembler.ts

fix: invalid initial accumulated data in `VisualizationAssembler`

---

backend_py/primary/primary/routers/well_completions/router.py
frontend/src/api/autogen/types.gen.ts
frontend/src/modules/WellCompletions/settings/atoms/queryAtoms.ts

Change arg to be `int | str | null` instead of `int | list[str] | null`

Add encoding of realizations array for endpoint
